### ISSUE TITLE
"!Playlist [name] play" is not a command?

### ISSUE THREAD

**Issue by Raeyn** [Phxntxm/Bonfire#21]
I can allow playlists (!allowplaylists on), import YouTube playlists (!import [playlist url]), create playlists (!playlist create), add/remove songs to a playlist (!playlist edit -> [name] -> add -> [songname]), view all our playlists (!playlists), view the songs in a playlist (!playlist or !playlist edit -> [name] -> list), activate playlists (!playlist edit -> [name] -> activate), delete playlists  (!playlist edit -> [name] -> delete)...

**but there is no command to play a playlist?!**

Tried:
!playlist [playlist]
!playlist [playlist] play
![playlist] play
![playlist]
!play playlist [playlist]
!play [playlist]
!activate [playlist]
!queue [playlist]
!playlist edit -> [playlist] -> play ("quit" after, none of the aforementioned commands were tested before quitting !playlist edit)

Am I missing the obvious?

**Comment by Phxntxm** [comment]
What you're missing is the queuetype. The `playlist` creation saves it as your own personal playlist; in order to play one of these in a server, the `queuetype` has to be DJ. Then you use the `dj` command to join the DJ queue, which will rotate through the DJ's and their playlists. The setup is exactly like https://plug.dj/ or https://www.dubtrack.fm/
